# -*- coding: utf-8 -*-
"""PostgreSQL schema（存储后端 P2）。

DDL 单一真理源：运行时建表（``PGStore.ensure_schema``）与迁移脚本
（``ops/migrate_sqlite_to_pg.py``）共用这一份，避免出现第二套漂移的 DDL
（历史遗留的 ``ops/pg_migrate.py`` 只有 8 张表且类型与主 schema 不一致）。

逐条存放在 ``DDL_STATEMENTS`` 里，**不按 ``;`` 拆分**——psycopg3 走扩展协议，
一次 execute 只允许一条语句；元组形式还能精确定位失败的是哪一条。

类型约定（与 SQLite schema 的对应关系）：

- 主键：``INTEGER PRIMARY KEY`` → ``BIGINT GENERATED BY DEFAULT AS IDENTITY``
  （``BY DEFAULT`` 允许迁移脚本显式插 id，无需 ``OVERRIDING SYSTEM VALUE``）
- 浮点：``REAL`` → ``DOUBLE PRECISION``（PG 的 ``real`` 只有 4 字节精度）
- 布尔：SQLite 的 ``INTEGER`` 0/1 → 真 ``BOOLEAN``
  （转换只在 ``pg_store`` 的 params 组装里做，SQLiteStore 侧不变）
- 时间：**保持 TEXT ISO-8601**——``_dt()`` 解包、时间窗的字典序比较、
  各处 datetime 运算全部零改动；转 TIMESTAMPTZ 会让 ``fromisoformat(datetime)`` 报错
- JSON：**保持 TEXT**（evidence_ids / metadata / meta / sparse）

约束：本模块的 SQL 里**禁止出现字面量 ``%`` 与字面量 ``?``**——
``pg_store._q()`` 用 ``sql.replace("?", "%s")`` 做占位符适配，字面量会破坏替换；
``%`` 在 psycopg3 的参数化里需写成 ``%%``。
"""
from __future__ import annotations

# bge-m3 稠密向量维度。只有该维度才投影到 pgvector 的 vector 列并建 HNSW 索引；
# 其它维度（如测试用的 dim=4）search_vectors 返回 None，由 retrieval 的
# numpy 全量余弦降级兜底（沿用既有契约）。
VECTOR_DIM = 1024

# 迁移与 TRUNCATE 的表顺序：父表在前，保证 REFERENCES 可满足。
TABLES_IN_FK_ORDER: tuple[str, ...] = (
    "nodes",
    "evidence",
    "facts",
    "edges",
    "versions",
    "beliefs",
    "intents",
    "impacts",
    "patterns",
    "triggers",
    "memory_links",
    "tombstones",
    "audit_log",
    "node_vectors",
    "vector_index_meta",
)

# 承载自增主键的表（迁移后需要 setval 重置序列）
IDENTITY_TABLES: tuple[str, ...] = (
    "nodes", "edges", "facts", "versions", "tombstones", "audit_log",
    "beliefs", "intents", "evidence", "memory_links", "impacts",
    "triggers", "patterns",
)

# 迁移时需要逐列比对的表（含 PG 专有的 data_version 之外的全部业务表）
PARITY_TABLES: tuple[str, ...] = TABLES_IN_FK_ORDER


DDL_STATEMENTS: tuple[str, ...] = (
    "CREATE EXTENSION IF NOT EXISTS vector",

    # ---------------- nodes ----------------
    """CREATE TABLE IF NOT EXISTS nodes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_type TEXT NOT NULL CHECK (node_type IN ('event','entity')),
  kind TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  ts TEXT,
  value_score DOUBLE PRECISION NOT NULL,
  protected BOOLEAN NOT NULL DEFAULT FALSE,
  access_label TEXT NOT NULL DEFAULT 'public',
  lifecycle TEXT NOT NULL DEFAULT 'active',
  life DOUBLE PRECISION NOT NULL,
  decay_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
  last_access TEXT,
  created_at TEXT NOT NULL,
  idempotency_key TEXT UNIQUE,
  evidence_ids TEXT NOT NULL DEFAULT '[]',
  source TEXT NOT NULL DEFAULT ''
)""",
    "CREATE INDEX IF NOT EXISTS idx_nodes_ts ON nodes(ts)",
    "CREATE INDEX IF NOT EXISTS idx_nodes_life ON nodes(lifecycle)",

    # ---------------- edges ----------------
    """CREATE TABLE IF NOT EXISTS edges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_id BIGINT NOT NULL REFERENCES nodes(id),
  to_id BIGINT NOT NULL REFERENCES nodes(id),
  relation_type TEXT NOT NULL,
  weight DOUBLE PRECISION NOT NULL,
  confidence DOUBLE PRECISION NOT NULL,
  valid_at TEXT NOT NULL,
  invalid_at TEXT,
  created_at TEXT NOT NULL,
  last_access TEXT,
  access_count INTEGER NOT NULL DEFAULT 0,
  lifecycle TEXT NOT NULL DEFAULT 'active',
  idempotency_key TEXT UNIQUE
)""",
    "CREATE INDEX IF NOT EXISTS idx_edges_from ON edges(from_id)",
    "CREATE INDEX IF NOT EXISTS idx_edges_to ON edges(to_id)",
    "CREATE INDEX IF NOT EXISTS idx_edges_rel ON edges(relation_type)",

    # ---------------- facts ----------------
    """CREATE TABLE IF NOT EXISTS facts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_id BIGINT NOT NULL REFERENCES nodes(id),
  fact_key TEXT NOT NULL,
  fact_value TEXT NOT NULL,
  source TEXT NOT NULL,
  confidence DOUBLE PRECISION NOT NULL,
  valid_at TEXT NOT NULL,
  recorded_at TEXT NOT NULL,
  invalid_at TEXT,
  superseded_by BIGINT,
  tombstoned BOOLEAN NOT NULL DEFAULT FALSE,
  idempotency_key TEXT UNIQUE,
  evidence_ids TEXT NOT NULL DEFAULT '[]',
  explicit_confirmation BOOLEAN NOT NULL DEFAULT FALSE
)""",
    "CREATE INDEX IF NOT EXISTS idx_facts_key ON facts(node_id, fact_key)",

    # ---------------- versions ----------------
    """CREATE TABLE IF NOT EXISTS versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_id BIGINT NOT NULL REFERENCES nodes(id),
  version INTEGER NOT NULL,
  content TEXT NOT NULL,
  created_at TEXT NOT NULL
)""",

    # ---------------- tombstones ----------------
    """CREATE TABLE IF NOT EXISTS tombstones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_type TEXT NOT NULL,
  target_id BIGINT NOT NULL,
  reason TEXT NOT NULL,
  tombstoned_at TEXT NOT NULL
)""",

    # ---------------- audit_log ----------------
    """CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  op TEXT NOT NULL,
  target_type TEXT,
  target_id BIGINT,
  reason TEXT,
  meta TEXT,
  at TEXT NOT NULL
)""",

    # ---------------- beliefs ----------------
    """CREATE TABLE IF NOT EXISTS beliefs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id BIGINT NOT NULL REFERENCES nodes(id),
  proposition TEXT NOT NULL,
  polarity TEXT NOT NULL DEFAULT 'neutral',
  confidence DOUBLE PRECISION NOT NULL,
  source TEXT NOT NULL DEFAULT 'chat',
  valid_at TEXT,
  invalid_at TEXT,
  superseded_by BIGINT,
  lifecycle TEXT NOT NULL DEFAULT 'active',
  access_label TEXT NOT NULL DEFAULT 'public',
  evidence_ids TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL,
  idempotency_key TEXT UNIQUE
)""",
    "CREATE INDEX IF NOT EXISTS idx_beliefs_subject ON beliefs(subject_id)",

    # ---------------- intents ----------------
    """CREATE TABLE IF NOT EXISTS intents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id BIGINT NOT NULL REFERENCES nodes(id),
  proposition TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  confidence DOUBLE PRECISION NOT NULL DEFAULT 0.7,
  source TEXT NOT NULL DEFAULT 'chat',
  valid_at TEXT,
  invalid_at TEXT,
  lifecycle TEXT NOT NULL DEFAULT 'active',
  access_label TEXT NOT NULL DEFAULT 'public',
  evidence_ids TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL,
  idempotency_key TEXT UNIQUE
)""",
    "CREATE INDEX IF NOT EXISTS idx_intents_subject ON intents(subject_id)",

    # ---------------- evidence ----------------
    """CREATE TABLE IF NOT EXISTS evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type TEXT NOT NULL,
  source_ref TEXT NOT NULL DEFAULT '',
  conversation_id TEXT,
  message_id TEXT,
  observed_at TEXT,
  content_hash TEXT,
  trust_level DOUBLE PRECISION,
  metadata TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  idempotency_key TEXT UNIQUE,
  access_label TEXT NOT NULL DEFAULT 'public'
)""",

    # ---------------- memory_links ----------------
    """CREATE TABLE IF NOT EXISTS memory_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id BIGINT NOT NULL,
  target_id BIGINT NOT NULL,
  source_type TEXT NOT NULL,
  relation TEXT NOT NULL,
  confidence DOUBLE PRECISION NOT NULL DEFAULT 0.7,
  valid_at TEXT,
  invalid_at TEXT,
  idempotency_key TEXT UNIQUE,
  source_dim TEXT NOT NULL DEFAULT ''
)""",
    "CREATE INDEX IF NOT EXISTS idx_memory_links_source ON memory_links(source_id)",
    "CREATE INDEX IF NOT EXISTS idx_memory_links_target ON memory_links(target_id)",

    # ---------------- impacts ----------------
    """CREATE TABLE IF NOT EXISTS impacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id BIGINT NOT NULL REFERENCES nodes(id),
  dimension TEXT NOT NULL,
  direction TEXT NOT NULL,
  valence TEXT NOT NULL,
  magnitude DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  kind TEXT NOT NULL DEFAULT 'objective',
  evaluator TEXT NOT NULL DEFAULT 'agent',
  description TEXT NOT NULL DEFAULT '',
  cause_event_id BIGINT,
  source TEXT NOT NULL DEFAULT 'chat',
  confidence DOUBLE PRECISION NOT NULL DEFAULT 0.7,
  valid_at TEXT,
  invalid_at TEXT,
  superseded_by BIGINT,
  lifecycle TEXT NOT NULL DEFAULT 'active',
  access_label TEXT NOT NULL DEFAULT 'public',
  evidence_ids TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL,
  idempotency_key TEXT UNIQUE
)""",
    "CREATE INDEX IF NOT EXISTS idx_impacts_subject_dim ON impacts(subject_id, dimension)",

    # ---------------- triggers ----------------
    """CREATE TABLE IF NOT EXISTS triggers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  memory_id BIGINT NOT NULL,
  memory_type TEXT NOT NULL,
  trigger_type TEXT NOT NULL,
  text TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'rule',
  confidence DOUBLE PRECISION NOT NULL DEFAULT 0.7,
  created_at TEXT NOT NULL,
  idempotency_key TEXT UNIQUE
)""",
    "CREATE INDEX IF NOT EXISTS idx_triggers_text ON triggers(text)",
    "CREATE INDEX IF NOT EXISTS idx_triggers_mem ON triggers(memory_type, memory_id)",

    # ---------------- patterns ----------------
    """CREATE TABLE IF NOT EXISTS patterns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pattern_type TEXT NOT NULL,
  subject_id BIGINT NOT NULL REFERENCES nodes(id),
  proposition TEXT NOT NULL,
  confidence DOUBLE PRECISION NOT NULL DEFAULT 0.7,
  support INTEGER NOT NULL DEFAULT 1,
  window_days INTEGER,
  source TEXT NOT NULL DEFAULT 'inferred',
  evidence_ids TEXT NOT NULL DEFAULT '[]',
  valid_at TEXT,
  created_at TEXT NOT NULL,
  idempotency_key TEXT UNIQUE
)""",
    "CREATE INDEX IF NOT EXISTS idx_patterns_subject_type ON patterns(subject_id, pattern_type)",

    # ---------------- node_vectors（pgvector 双列）----------------
    # dense：ANN 列，仅 VECTOR_DIM 维度的向量有值（其余为 NULL 走 numpy 降级）
    # dense_json：原始 JSON 文本，保真 + 降级数据源 + 迁移逐字节对拍
    """CREATE TABLE IF NOT EXISTS node_vectors (
  node_id BIGINT PRIMARY KEY REFERENCES nodes(id),
  dense vector(1024),
  dense_json TEXT NOT NULL,
  sparse TEXT,
  model TEXT NOT NULL,
  dim INTEGER NOT NULL,
  updated_at TEXT NOT NULL
)""",
    """CREATE INDEX IF NOT EXISTS idx_node_vectors_hnsw
  ON node_vectors USING hnsw (dense vector_cosine_ops)
  WITH (m = 16, ef_construction = 64)""",

    # ---------------- vector_index_meta ----------------
    """CREATE TABLE IF NOT EXISTS vector_index_meta (
  model TEXT PRIMARY KEY,
  dim INTEGER NOT NULL,
  updated_at TEXT NOT NULL
)""",

    # ---------------- data_version（PG 专有：跨进程邻接缓存失效）----------------
    """CREATE TABLE IF NOT EXISTS data_version (
  scope TEXT PRIMARY KEY,
  version BIGINT NOT NULL DEFAULT 0
)""",
    "INSERT INTO data_version(scope, version) VALUES ('edges', 0) "
    "ON CONFLICT (scope) DO NOTHING",
)


def ddl_text() -> str:
    """返回带分号的完整 DDL 文本（供打印/审阅；执行请用 DDL_STATEMENTS）。"""
    return ";\n".join(DDL_STATEMENTS) + ";"
