# -*- coding: utf-8 -*-
"""SQLite → PostgreSQL 数据迁移（存储后端 P3）。

用法：
  py ops/migrate_sqlite_to_pg.py --src ops/data/lccc_memory.db \
     --dsn postgresql://dnatest:dnatest@127.0.0.1:5433/dnamemory --truncate

特性：
- 源库**只读**打开（``file:...?mode=ro``）——迁移永不改动源库，原库始终是权威副本，
  PG 侧 ``--truncate`` 可反复重跑。
- PG 建表复用 ``dnamemory.pg_schema.DDL_STATEMENTS``（单一真理源，不另立一套 DDL）。
- **id 保真**：显式插 id 列（PG 主键是 ``GENERATED BY DEFAULT``），搬完逐表
  ``setval`` 重置序列，使后续 insert 不与既有 id 相撞。
- **向量**：源 ``dense``（JSON 文本）原样进 ``dense_json``（保真 + numpy 降级数据源）；
  仅当 ``dim == VECTOR_DIM`` 时归一化后写入 pgvector 的 ``dense`` 列，否则留 NULL。
- **一致性报告**：逐表行数 / id 范围 / 序列值 / 抽样逐列比对 / FK 孤儿检查
  → ``ops/data/migration_report.json``；有任何不一致则退出码 1。
"""
from __future__ import annotations

import argparse
import json
import sqlite3
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from dnamemory.pg_schema import (DDL_STATEMENTS, IDENTITY_TABLES,  # noqa: E402
                                 TABLES_IN_FK_ORDER, VECTOR_DIM)

BATCH = 2000
DEFAULT_REPORT = ROOT / "ops" / "data" / "migration_report.json"

# SQLite 用 INTEGER 0/1 存布尔，PG 是真 BOOLEAN（与 pg_schema 的类型约定对应）
BOOL_COLUMNS: dict[str, set[str]] = {
    "nodes": {"protected"},
    "facts": {"tombstoned", "explicit_confirmation"},
}

# 主键列：迁移与抽样比对按此定位行（node_vectors 主键是 node_id 而非 id；
# vector_index_meta 是 TEXT 主键 model，抽样比对对它跳过）
PK_COLUMNS: dict[str, str] = {"node_vectors": "node_id", "vector_index_meta": "model"}
TEXT_PK_TABLES = {"vector_index_meta"}


def _pk_col(table: str) -> str:
    return PK_COLUMNS.get(table, "id")


# FK 列表：迁移后逐列做孤儿检查（列 → 被引用表）
FK_CHECKS: tuple[tuple[str, str, str], ...] = (
    ("edges", "from_id", "nodes"),
    ("edges", "to_id", "nodes"),
    ("facts", "node_id", "nodes"),
    ("versions", "node_id", "nodes"),
    ("beliefs", "subject_id", "nodes"),
    ("intents", "subject_id", "nodes"),
    ("impacts", "subject_id", "nodes"),
    ("patterns", "subject_id", "nodes"),
    ("node_vectors", "node_id", "nodes"),
)


def _force_utf8():
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:  # noqa: BLE001
            pass


# ---------------- 向量工具 ----------------

def _vec_literal(vec) -> str:
    """numpy 数组 → pgvector 字面量 '[1,2,3]'。"""
    return "[" + ",".join(f"{float(x):.7g}" for x in vec) + "]"


def _normalized(vec_json: str, dim: int):
    """JSON 文本 → L2 归一化后的 pgvector 字面量；零向量/维度不符/解析失败返回 None。

    None 表示该行不投影到 ANN 列——search_vectors 会因 dim 不匹配返回 None，
    由 retrieval._dense_path 的 numpy 全量余弦降级兜底。
    """
    if int(dim) != VECTOR_DIM:
        return None
    try:
        import numpy as np
        a = np.asarray(json.loads(vec_json), dtype="float32")
        if a.size != VECTOR_DIM:
            return None
        n = float(np.linalg.norm(a))
        if n == 0.0 or not np.isfinite(n):
            return None
        return _vec_literal(a / n)
    except Exception:  # noqa: BLE001
        return None


# ---------------- 结构探测 ----------------

def _sqlite_columns(con, table: str) -> list[str]:
    return [r[1] for r in con.execute(f"PRAGMA table_info({table})")]


def _pg_columns(con, table: str) -> list[str]:
    rows = con.execute(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_name = %s AND table_schema = current_schema() "
        "ORDER BY ordinal_position", (table,)).fetchall()
    return [r[0] for r in rows]


def _table_exists(con, table: str) -> bool:
    return con.execute(
        "SELECT 1 FROM information_schema.tables "
        "WHERE table_name = %s AND table_schema = current_schema()",
        (table,)).fetchone() is not None


# ---------------- 搬运 ----------------

def _column_pairs(table: str, src_cols: list[str],
                  pg_cols: list[str]) -> list[tuple[str, str]]:
    """返回 (源列, 目标列) 对，源旧库缺列时自动跳过。

    普通表两侧同名；node_vectors 的 ``dense``(TEXT JSON) 改名进 ``dense_json``
    （PG 的 ``dense`` 是 vector 列，由 ``_project_vectors`` 归一化后单独写入）。
    """
    if table == "node_vectors":
        pairs: list[tuple[str, str]] = []
        for c in src_cols:
            if c == "dense":
                if "dense_json" in pg_cols:
                    pairs.append(("dense", "dense_json"))
                continue
            if c in pg_cols:
                pairs.append((c, c))
        return pairs
    return [(c, c) for c in src_cols if c in pg_cols]


def _insert_sql(table: str, cols: list[str]) -> str:
    parts = ["%s::vector" if (table == "node_vectors" and c == "dense") else "%s"
             for c in cols]
    return (f"INSERT INTO {table} ({','.join(cols)}) "
            f"VALUES ({','.join(parts)}) ON CONFLICT DO NOTHING")


def _convert_row(table: str, cols: list[str], row: tuple) -> tuple:
    bools = BOOL_COLUMNS.get(table, set())
    out = []
    for col, val in zip(cols, row):
        if col in bools and val is not None:
            out.append(bool(val))
        else:
            out.append(val)
    return tuple(out)


def _copy_table(src, dst, table: str, report: dict) -> None:
    src_cols = _sqlite_columns(src, table)
    pg_cols = _pg_columns(dst, table)
    pairs = _column_pairs(table, src_cols, pg_cols)
    if not pairs:
        report[table] = {"skipped": True, "reason": "无交集列"}
        return
    sel_cols = [s for s, _ in pairs]
    ins_cols = [d for _, d in pairs]

    insert_sql = _insert_sql(table, ins_cols)
    cur = src.execute(
        f"SELECT {','.join(sel_cols)} FROM {table} ORDER BY {_pk_col(table)}")
    written = 0
    while True:
        rows = cur.fetchmany(BATCH)
        if not rows:
            break
        with dst.cursor() as dc:
            dc.executemany(insert_sql,
                           [_convert_row(table, ins_cols, r) for r in rows])
        written += len(rows)

    # node_vectors：把归一化后的向量投影到 pgvector 列
    if table == "node_vectors" and "dense" in src_cols:
        _project_vectors(src, dst)

    report[table] = {"copied": written, "columns": len(ins_cols)}


def _project_vectors(src, dst) -> None:
    """dense_json → dense(vector)，仅 VECTOR_DIM 且非零向量的行。"""
    cur = src.execute("SELECT node_id, dense, dim FROM node_vectors")
    batch, projected = [], 0
    while True:
        rows = cur.fetchmany(BATCH)
        if not rows:
            break
        for node_id, dense, dim in rows:
            lit = _normalized(dense, dim)
            batch.append((lit, node_id))
            if lit is not None:
                projected += 1
        with dst.cursor() as dc:
            dc.executemany(
                "UPDATE node_vectors SET dense = %s::vector WHERE node_id = %s",
                batch)
        batch = []
    print(f"    向量投影到 pgvector: {projected} 行")


def _reset_sequences(dst, tables: list[str]) -> dict:
    """按 MAX(id) 重置 identity 序列，避免后续 insert 撞既有 id。"""
    out = {}
    for t in tables:
        if t not in IDENTITY_TABLES or not _table_exists(dst, t):
            continue
        row = dst.execute(f"SELECT MAX(id) FROM {t}").fetchone()
        max_id = row[0] if row else None
        if max_id is None:
            dst.execute(
                "SELECT setval(pg_get_serial_sequence(%s, 'id'), 1, false)", (t,))
            out[t] = 1
        else:
            dst.execute(
                "SELECT setval(pg_get_serial_sequence(%s, 'id'), %s, true)",
                (t, max_id))
            out[t] = int(max_id)
    return out


# ---------------- 校验 ----------------

def _norm_scalar(v):
    if isinstance(v, bool):
        return int(v)
    if isinstance(v, float):
        return round(v, 9)
    return v


def _verify(src, dst, tables: list[str], sample: int) -> tuple[dict, list]:
    stats, mismatches = {}, []
    for t in tables:
        if not _table_exists(dst, t):
            continue
        src_n = src.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
        pg_n = dst.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
        entry = {"src_rows": src_n, "pg_rows": pg_n}
        if src_n != pg_n:
            mismatches.append(f"{t}: 行数 {src_n} != {pg_n}")

        pairs = _column_pairs(t, _sqlite_columns(src, t), _pg_columns(dst, t))
        if sample and pairs and t not in TEXT_PK_TABLES:
            pk = _pk_col(t)
            src_sel = ",".join(s for s, _ in pairs)
            dst_sel = ",".join(d for _, d in pairs)
            ids = [r[0] for r in src.execute(
                f"SELECT {pk} FROM {t} ORDER BY {pk} LIMIT {int(sample)}")]
            bad = 0
            for rid in ids:
                srow = src.execute(
                    f"SELECT {src_sel} FROM {t} WHERE {pk} = ?",
                    (rid,)).fetchone()
                prow = dst.execute(
                    f"SELECT {dst_sel} FROM {t} WHERE {pk} = %s",
                    (rid,)).fetchone()
                if srow is None or prow is None:
                    bad += 1
                    continue
                for (_sc, dcol), a, b in zip(pairs, srow, prow):
                    if dcol in BOOL_COLUMNS.get(t, set()):
                        if bool(a) != bool(b):
                            bad += 1
                    elif _norm_scalar(a) != _norm_scalar(b):
                        bad += 1
                        if len(mismatches) < 20:
                            mismatches.append(
                                f"{t}#{rid}.{dcol}: {a!r} != {b!r}")
            entry["sampled"] = len(ids)
            entry["sample_mismatches"] = bad
            if bad:
                mismatches.append(f"{t}: 抽样 {bad} 处不一致")
        stats[t] = entry

    orphans = {}
    for table, col, ref in FK_CHECKS:
        if not _table_exists(dst, table):
            continue
        n = dst.execute(
            f"SELECT COUNT(*) FROM {table} x LEFT JOIN {ref} r "
            f"ON r.id = x.{col} WHERE x.{col} IS NOT NULL AND r.id IS NULL"
        ).fetchone()[0]
        orphans[f"{table}.{col}"] = n
        if n:
            mismatches.append(f"孤儿引用 {table}.{col} → {ref}: {n} 行")
    return {"tables": stats, "orphans": orphans}, mismatches


# ---------------- 主流程 ----------------

def migrate(args) -> dict:
    import psycopg

    src_path = Path(args.src).resolve()
    if not src_path.exists():
        raise SystemExit(f"源库不存在: {src_path}")

    src = sqlite3.connect(f"file:{src_path}?mode=ro", uri=True)
    report = {
        "ok": False, "src": str(src_path), "dsn": args.dsn,
        "started_at": datetime.now().isoformat(timespec="seconds"),
        "tables": {}, "mismatches": [],
    }
    try:
        with psycopg.connect(args.dsn, autocommit=True) as dst:
            print("1) 建表（复用 pg_schema.DDL_STATEMENTS）")
            for stmt in DDL_STATEMENTS:
                dst.execute(stmt)
            dst.execute("SELECT pg_advisory_lock(918273645)")   # 防并发迁移

            if args.dry_run:
                print("\n[dry-run] 仅统计源表行数，不写 PG：")
                for t in TABLES_IN_FK_ORDER:
                    n = src.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0]
                    print(f"    {t:20s} {n}")
                report["ok"] = True
                report["dry_run"] = True
                return report

            if args.append:
                print("2) 追加模式（ON CONFLICT DO NOTHING，不清理目标表）")
            else:
                print("2) 清空目标表（TRUNCATE ... RESTART IDENTITY CASCADE）")
                dst.execute("TRUNCATE " + ", ".join(TABLES_IN_FK_ORDER)
                            + " RESTART IDENTITY CASCADE")

            print("3) 逐表搬运")
            for t in TABLES_IN_FK_ORDER:
                _copy_table(src, dst, t, report["tables"])
                info = report["tables"][t]
                if not info.get("skipped"):
                    print(f"    {t:20s} {info['copied']:>6} 行")

            print("4) 重置 identity 序列")
            report["sequences"] = _reset_sequences(dst, list(TABLES_IN_FK_ORDER))

            print("5) 一致性校验")
            checks, mismatches = _verify(src, dst, list(TABLES_IN_FK_ORDER),
                                         args.sample)
            report.update(checks)
            report["mismatches"] = mismatches
            report["ok"] = not mismatches
    finally:
        src.close()

    report["finished_at"] = datetime.now().isoformat(timespec="seconds")
    return report


def main():
    _force_utf8()
    p = argparse.ArgumentParser(description="SQLite → PostgreSQL 数据迁移")
    p.add_argument("--src", required=True, help="源 SQLite 库路径（只读打开）")
    p.add_argument("--dsn", required=True, help="目标 PostgreSQL DSN")
    mode = p.add_mutually_exclusive_group()
    mode.add_argument("--truncate", action="store_true", default=True,
                      help="迁移前清空目标表（默认）")
    mode.add_argument("--append", action="store_true",
                      help="追加模式，不清理目标表")
    p.add_argument("--dry-run", action="store_true", help="只统计不写库")
    p.add_argument("--sample", type=int, default=200,
                   help="每表抽样逐列比对的 id 数（0=跳过抽样）")
    p.add_argument("--report", default=str(DEFAULT_REPORT),
                   help="一致性报告输出路径")
    args = p.parse_args()

    report = migrate(args)

    out = Path(args.report)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, ensure_ascii=False, indent=1),
                   encoding="utf-8")

    print()
    if report["ok"]:
        print(f"迁移完成，一致性校验通过。报告: {out}")
    else:
        print(f"迁移存在不一致（{len(report['mismatches'])} 项）：")
        for m in report["mismatches"][:15]:
            print("  -", m)
        print(f"报告: {out}")
        sys.exit(1)


if __name__ == "__main__":
    main()
